################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
build/CMakeFiles/3.16.3/CompilerIdC \
build/CMakeFiles/3.16.3/CompilerIdCXX \
build/CMakeFiles/gme_carel.elf.dir \
build/app_trace \
build/app_update \
build/asio/asio/asio/src \
build/bootloader/CMakeFiles/3.16.3/CompilerIdC \
build/bootloader/CMakeFiles/3.16.3/CompilerIdCXX \
build/bootloader/CMakeFiles/bootloader.elf.dir \
build/bootloader/bootloader_support \
build/bootloader/bootloader_support/src \
build/bootloader/bootloader_support/src/esp32 \
build/bootloader/bootloader_support/src/secure_boot_v1 \
build/bootloader/efuse/esp32 \
build/bootloader/efuse/src/esp32 \
build/bootloader/efuse/src \
build/bootloader/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/__/__ \
build/bootloader/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src \
build/bootloader/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp32 \
build/bootloader/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32 \
build/bootloader/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp32 \
build/bootloader/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src \
build/bootloader/esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir \
build/bootloader/esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32 \
build/bootloader/esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches \
build/bootloader/esp-idf/hal/CMakeFiles/__idf_hal.dir \
build/bootloader/esp-idf/log/CMakeFiles/__idf_log.dir \
build/bootloader/esp-idf/main/CMakeFiles/__idf_main.dir \
build/bootloader/esp-idf/micro-ecc/CMakeFiles/__idf_micro-ecc.dir \
build/bootloader/esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32 \
build/bootloader/esp-idf/soc/CMakeFiles/__idf_soc.dir \
build/bootloader/esp-idf/spi_flash/CMakeFiles/__idf_spi_flash.dir/esp32 \
build/bootloader/esp_hw_support \
build/bootloader/esp_hw_support/port/esp32 \
build/bootloader/esp_rom/patches \
build/bootloader/hal \
build/bootloader/hal/esp32 \
build/bootloader/log \
build/bootloader/main \
build/bootloader/micro-ecc \
build/bootloader \
build/bootloader/soc/esp32 \
build/bootloader/soc \
build/bootloader/spi_flash/esp32 \
build/bootloader/xtensa \
build/bootloader/xtensa/esp32 \
build/bootloader_support \
build/bootloader_support/src \
build/bootloader_support/src/idf \
build/bootloader_support/src/secure_boot_v1 \
build/cbor/tinycbor/src \
build/coap/libcoap/src \
build/coap/port \
build/console/argtable3 \
build/console \
build/console/linenoise \
build/cxx \
build/driver \
build/driver/esp32 \
build/efuse/esp32 \
build/efuse/src/esp32 \
build/efuse/src \
build/esp-idf/app_trace/CMakeFiles/__idf_app_trace.dir \
build/esp-idf/app_trace/CMakeFiles/__idf_app_trace.dir/gcov \
build/esp-idf/app_update/CMakeFiles/__idf_app_update.dir \
build/esp-idf/asio/CMakeFiles/__idf_asio.dir/asio/asio/src \
build/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/__/__ \
build/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src \
build/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/idf \
build/esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/secure_boot_v1 \
build/esp-idf/cbor/CMakeFiles/__idf_cbor.dir/tinycbor/src \
build/esp-idf/cmock/CMakeFiles/__idf_cmock.dir/CMock/src \
build/esp-idf/coap/CMakeFiles/__idf_coap.dir/libcoap/src \
build/esp-idf/coap/CMakeFiles/__idf_coap.dir/port \
build/esp-idf/console/CMakeFiles/__idf_console.dir/argtable3 \
build/esp-idf/console/CMakeFiles/__idf_console.dir \
build/esp-idf/console/CMakeFiles/__idf_console.dir/linenoise \
build/esp-idf/cxx/CMakeFiles/__idf_cxx.dir \
build/esp-idf/driver/CMakeFiles/__idf_driver.dir \
build/esp-idf/driver/CMakeFiles/__idf_driver.dir/esp32 \
build/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32 \
build/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp32 \
build/esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src \
build/esp-idf/esp-tls/CMakeFiles/__idf_esp-tls.dir/esp-tls-crypto \
build/esp-idf/esp-tls/CMakeFiles/__idf_esp-tls.dir \
build/esp-idf/esp32/CMakeFiles/__idf_esp32.dir \
build/esp-idf/esp_adc_cal/CMakeFiles/__idf_esp_adc_cal.dir \
build/esp-idf/esp_common/CMakeFiles/__idf_esp_common.dir/src \
build/esp-idf/esp_event/CMakeFiles/__idf_esp_event.dir \
build/esp-idf/esp_gdbstub/CMakeFiles/__idf_esp_gdbstub.dir/esp32 \
build/esp-idf/esp_gdbstub/CMakeFiles/__idf_esp_gdbstub.dir/src \
build/esp-idf/esp_gdbstub/CMakeFiles/__idf_esp_gdbstub.dir/xtensa \
build/esp-idf/esp_hid/CMakeFiles/__idf_esp_hid.dir/src \
build/esp-idf/esp_http_client/CMakeFiles/__idf_esp_http_client.dir \
build/esp-idf/esp_http_client/CMakeFiles/__idf_esp_http_client.dir/lib \
build/esp-idf/esp_http_server/CMakeFiles/__idf_esp_http_server.dir/src \
build/esp-idf/esp_http_server/CMakeFiles/__idf_esp_http_server.dir/src/util \
build/esp-idf/esp_https_ota/CMakeFiles/__idf_esp_https_ota.dir/src \
build/esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir \
build/esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32 \
build/esp-idf/esp_ipc/CMakeFiles/__idf_esp_ipc.dir \
build/esp-idf/esp_local_ctrl/CMakeFiles/__idf_esp_local_ctrl.dir/proto-c \
build/esp-idf/esp_local_ctrl/CMakeFiles/__idf_esp_local_ctrl.dir/src \
build/esp-idf/esp_netif/CMakeFiles/__idf_esp_netif.dir \
build/esp-idf/esp_netif/CMakeFiles/__idf_esp_netif.dir/loopback \
build/esp-idf/esp_netif/CMakeFiles/__idf_esp_netif.dir/lwip \
build/esp-idf/esp_pm/CMakeFiles/__idf_esp_pm.dir \
build/esp-idf/esp_ringbuf/CMakeFiles/__idf_esp_ringbuf.dir \
build/esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches \
build/esp-idf/esp_serial_slave_link/CMakeFiles/__idf_esp_serial_slave_link.dir \
build/esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir \
build/esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/arch/xtensa \
build/esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port \
build/esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/soc/esp32 \
build/esp-idf/esp_timer/CMakeFiles/__idf_esp_timer.dir/src \
build/esp-idf/esp_websocket_client/CMakeFiles/__idf_esp_websocket_client.dir \
build/esp-idf/esp_wifi/CMakeFiles/__idf_esp_wifi.dir/esp32 \
build/esp-idf/esp_wifi/CMakeFiles/__idf_esp_wifi.dir/src \
build/esp-idf/espcoredump/CMakeFiles/__idf_espcoredump.dir/src \
build/esp-idf/espcoredump/CMakeFiles/__idf_espcoredump.dir/src/port/xtensa \
build/esp-idf/expat/CMakeFiles/__idf_expat.dir/expat/expat/lib \
build/esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/diskio \
build/esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/port/freertos \
build/esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/src \
build/esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/vfs \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/common \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus/ascii \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus/functions \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus/rtu \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/modbus/tcp \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/port \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/serial_master/modbus_controller \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/serial_slave/modbus_controller \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/tcp_master/modbus_controller \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/tcp_master/port \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/tcp_slave/modbus_controller \
build/esp-idf/freemodbus/CMakeFiles/__idf_freemodbus.dir/tcp_slave/port \
build/esp-idf/freertos/CMakeFiles/__idf_freertos.dir \
build/esp-idf/freertos/CMakeFiles/__idf_freertos.dir/port \
build/esp-idf/freertos/CMakeFiles/__idf_freertos.dir/port/xtensa \
build/esp-idf/hal/CMakeFiles/__idf_hal.dir \
build/esp-idf/hal/CMakeFiles/__idf_hal.dir/esp32 \
build/esp-idf/heap/CMakeFiles/__idf_heap.dir \
build/esp-idf/jsmn/CMakeFiles/__idf_jsmn.dir/src \
build/esp-idf/json/CMakeFiles/__idf_json.dir/cJSON \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_auth \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_auth/hmacsha256 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_auth/hmacsha512 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_box \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_box/curve25519xchacha20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/ed25519 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/ed25519/ref10 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/hchacha20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/hsalsa20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_core/salsa/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_generichash/blake2b \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_generichash \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash/sha256/cp \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash/sha256 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash/sha512/cp \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_hash/sha512 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_kdf/blake2b \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_kdf \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_kx \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_onetimeauth \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash/argon2 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/ed25519/ref10 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_scalarmult/ristretto255/ref10 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_secretbox \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_secretbox/xchacha20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_secretstream/xchacha20poly1305 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_shorthash \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_shorthash/siphash24 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_sign \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_sign/ed25519 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/chacha20/dolbeau \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/chacha20/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/chacha20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa20/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa20/xmm6 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa20/xmm6int \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa2012/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa2012 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa208/ref \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/salsa208 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/xchacha20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_stream/xsalsa20 \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/crypto_verify/sodium \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/randombytes \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/libsodium/src/libsodium/sodium \
build/esp-idf/libsodium/CMakeFiles/__idf_libsodium.dir/port \
build/esp-idf/log/CMakeFiles/__idf_log.dir \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/apps/dhcpserver \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/apps/ping \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/apps/sntp \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/api \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/apps/netbiosns \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/apps/sntp \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/core \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/core/ipv4 \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/core/ipv6 \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/netif \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/netif/ppp \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/lwip/src/netif/ppp/polarssl \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32/debug \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32/freertos \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32/hooks \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32/netif \
build/esp-idf/lwip/CMakeFiles/__idf_lwip.dir/port/esp32 \
build/esp-idf/main/CMakeFiles/__idf_main.dir \
build/esp-idf/main/CMakeFiles/__idf_main.dir/tinycbor \
build/esp-idf/mbedtls/CMakeFiles/__idf_mbedtls.dir/esp_crt_bundle \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/aes/block \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/aes \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/md \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/__/__/port/sha/parallel_engine \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedtls.dir/__/__/port \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedtls.dir \
build/esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedx509.dir \
build/esp-idf/mdns/CMakeFiles/__idf_mdns.dir \
build/esp-idf/modem/CMakeFiles/__idf_modem.dir/src \
build/esp-idf/mqtt/CMakeFiles/__idf_mqtt.dir/esp-mqtt/lib \
build/esp-idf/mqtt/CMakeFiles/__idf_mqtt.dir/esp-mqtt \
build/esp-idf/newlib/CMakeFiles/__idf_newlib.dir \
build/esp-idf/newlib/CMakeFiles/__idf_newlib.dir/port \
build/esp-idf/nghttp/CMakeFiles/__idf_nghttp.dir/nghttp2/lib \
build/esp-idf/nghttp/CMakeFiles/__idf_nghttp.dir/port \
build/esp-idf/nvs_flash/CMakeFiles/__idf_nvs_flash.dir/src \
build/esp-idf/openssl/CMakeFiles/__idf_openssl.dir/library \
build/esp-idf/openssl/CMakeFiles/__idf_openssl.dir/platform \
build/esp-idf/perfmon/CMakeFiles/__idf_perfmon.dir \
build/esp-idf/protobuf-c/CMakeFiles/__idf_protobuf-c.dir/protobuf-c/protobuf-c \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/proto-c \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/common \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/security \
build/esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/transports \
build/esp-idf/pthread/CMakeFiles/__idf_pthread.dir \
build/esp-idf/sdmmc/CMakeFiles/__idf_sdmmc.dir \
build/esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32 \
build/esp-idf/soc/CMakeFiles/__idf_soc.dir \
build/esp-idf/spi_flash/CMakeFiles/__idf_spi_flash.dir \
build/esp-idf/spi_flash/CMakeFiles/__idf_spi_flash.dir/esp32 \
build/esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir \
build/esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/spiffs/src \
build/esp-idf/tcp_transport/CMakeFiles/__idf_tcp_transport.dir \
build/esp-idf/tcpip_adapter/CMakeFiles/__idf_tcpip_adapter.dir \
build/esp-idf/ulp/CMakeFiles/__idf_ulp.dir \
build/esp-idf/unity/CMakeFiles/__idf_unity.dir/unity/src \
build/esp-idf/unity/CMakeFiles/__idf_unity.dir \
build/esp-idf/vfs/CMakeFiles/__idf_vfs.dir \
build/esp-idf/wear_levelling/CMakeFiles/__idf_wear_levelling.dir \
build/esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/proto-c \
build/esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/src \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/port \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/ap \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/common \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/crypto \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/eap_peer \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/esp_supplicant \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/rsn_supp \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/utils \
build/esp-idf/wpa_supplicant/CMakeFiles/__idf_wpa_supplicant.dir/src/wps \
build/esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir \
build/esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir/esp32 \
build/esp-tls/esp-tls-crypto \
build/esp-tls \
build/esp32 \
build/esp_adc_cal \
build/esp_common/src \
build/esp_eth/src \
build/esp_event \
build/esp_gdbstub/esp32 \
build/esp_gdbstub/src \
build/esp_gdbstub/xtensa \
build/esp_hid/src \
build/esp_http_client \
build/esp_http_client/lib \
build/esp_http_server/src \
build/esp_http_server/src/util \
build/esp_https_ota/src \
build/esp_hw_support \
build/esp_hw_support/port/esp32 \
build/esp_ipc \
build/esp_local_ctrl/proto-c \
build/esp_local_ctrl/src \
build/esp_netif \
build/esp_netif/loopback \
build/esp_netif/lwip \
build/esp_pm \
build/esp_ringbuf \
build/esp_rom/patches \
build/esp_serial_slave_link \
build/esp_system \
build/esp_system/port/arch/xtensa \
build/esp_system/port \
build/esp_system/port/soc/esp32 \
build/esp_timer/src \
build/esp_websocket_client \
build/esp_wifi/esp32 \
build/esp_wifi/src \
build/espcoredump/src \
build/espcoredump/src/port/xtensa \
build/expat/expat/expat/lib \
build/fatfs/diskio \
build/fatfs/port/freertos \
build/fatfs/src \
build/fatfs/vfs \
build/freemodbus/common \
build/freemodbus/modbus/ascii \
build/freemodbus/modbus/functions \
build/freemodbus/modbus \
build/freemodbus/modbus/rtu \
build/freemodbus/modbus/tcp \
build/freemodbus/port \
build/freemodbus/serial_master/modbus_controller \
build/freemodbus/serial_slave/modbus_controller \
build/freemodbus/tcp_master/modbus_controller \
build/freemodbus/tcp_master/port \
build/freemodbus/tcp_slave/modbus_controller \
build/freemodbus/tcp_slave/port \
build/freertos \
build/freertos/port \
build/freertos/port/xtensa \
build/hal \
build/hal/esp32 \
build/heap \
build/jsmn/src \
build/json/cJSON \
build/libsodium/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_auth \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha256 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
build/libsodium/libsodium/src/libsodium/crypto_box \
build/libsodium/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_core/ed25519 \
build/libsodium/libsodium/src/libsodium/crypto_core/ed25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_core/hchacha20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
build/libsodium/libsodium/src/libsodium/crypto_core/salsa/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash \
build/libsodium/libsodium/src/libsodium/crypto_hash \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha256/cp \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha256 \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha512/cp \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha512 \
build/libsodium/libsodium/src/libsodium/crypto_kdf/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_kdf \
build/libsodium/libsodium/src/libsodium/crypto_kx \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/argon2 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/ed25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/ristretto255/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_secretbox \
build/libsodium/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_shorthash \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24 \
build/libsodium/libsodium/src/libsodium/crypto_sign \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519 \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20 \
build/libsodium/libsodium/src/libsodium/crypto_stream \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20 \
build/libsodium/libsodium/src/libsodium/crypto_stream/xsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_verify/sodium \
build/libsodium/libsodium/src/libsodium/randombytes \
build/libsodium/libsodium/src/libsodium/sodium \
build/libsodium/port \
build/log \
build/lwip/apps/dhcpserver \
build/lwip/apps/ping \
build/lwip/apps/sntp \
build/lwip/lwip/src/api \
build/lwip/lwip/src/apps/netbiosns \
build/lwip/lwip/src/apps/sntp \
build/lwip/lwip/src/core \
build/lwip/lwip/src/core/ipv4 \
build/lwip/lwip/src/core/ipv6 \
build/lwip/lwip/src/netif \
build/lwip/lwip/src/netif/ppp \
build/lwip/lwip/src/netif/ppp/polarssl \
build/lwip/port/esp32/debug \
build/lwip/port/esp32/freertos \
build/lwip/port/esp32/hooks \
build/lwip/port/esp32/netif \
build/lwip/port/esp32 \
build/main \
build/main/tinycbor \
build/mbedtls/esp_crt_bundle \
build/mbedtls/mbedtls/library \
build/mbedtls/port/aes/block \
build/mbedtls/port/aes \
build/mbedtls/port \
build/mbedtls/port/md \
build/mbedtls/port/sha \
build/mbedtls/port/sha/parallel_engine \
build/mdns \
build/modem/src \
build/mqtt/esp-mqtt/lib \
build/mqtt/esp-mqtt \
build/newlib \
build/newlib/port \
build/nghttp/nghttp2/lib \
build/nghttp/port \
build/nvs_flash/src \
build/openssl/library \
build/openssl/platform \
build/perfmon \
build \
build/protobuf-c/protobuf-c/protobuf-c \
build/protocomm/proto-c \
build/protocomm/src/common \
build/protocomm/src/security \
build/protocomm/src/transports \
build/pthread \
build/sdmmc \
build/soc/esp32 \
build/soc \
build/spi_flash \
build/spi_flash/esp32 \
build/spiffs \
build/spiffs/spiffs/src \
build/tcp_transport \
build/tcpip_adapter \
build/ulp \
build/unity/unity/src \
build/unity \
build/vfs \
build/wear_levelling \
build/wifi_provisioning/proto-c \
build/wifi_provisioning/src \
build/wpa_supplicant/port \
build/wpa_supplicant/src/ap \
build/wpa_supplicant/src/common \
build/wpa_supplicant/src/crypto \
build/wpa_supplicant/src/eap_peer \
build/wpa_supplicant/src/esp_supplicant \
build/wpa_supplicant/src/rsn_supp \
build/wpa_supplicant/src/utils \
build/wpa_supplicant/src/wps \
build/xtensa \
build/xtensa/esp32 \
components/modem/src \
main \
main/tinycbor \

